name: ROMANA CHUDIK
favicon: null
layout_spectrum: 0.4749104
typography_spectrum: 0.9121864
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PHOTOGRAPHY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ecf8f8'
    - '#c5c5c5'
    - '#676767'
    - '#94b44a'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.3046595
  rhythmicContrast: 0.5
purpose: []
