name: ROMANA CHUDIK
favicon: null
layout_spectrum: 0.4749104
typography_spectrum: 0.9121864
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3009310376364738
  lightness: 1
  saturation: 0.3046595
  rhythmicContrast: 0.863399
purpose: []
